name: Atualizar Notícias

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-news:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repositório
        uses: actions/checkout@v4
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Instalar dependências
        run: pip install -r requirements.txt
      - name: Rodar script de coleta
        run: python scraper.py
      - name: Commit e Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add news.json bulletin.json
          git commit -m "Automated update: Coleta de novas notícias" || exit 0
          git push
